### ISSUE TITLE
Option to exclude files / folders

### ISSUE THREAD

**Issue by rajeshgoyalg** [easingthemes/ssh-deploy#27] opened 2021-01-25 12:41 UTC
Is it possible to add option to exclude files / folders like .git

**Comment by SergeShkurko** [comment] 2021-01-31 22:49
Duplicate of #26

**Comment by peterkracik** [comment] 2021-03-12 07:31
https://github.com/easingthemes/ssh-deploy/pull/32

**Comment by easingthemes** [comment] 2021-03-15 12:09
Thanks @peterkracik

**Closed** 2021-03-15 12:09 UTC
